[build]
  publish = "."

# Security and performance headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com data:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; script-src 'self' 'unsafe-inline'; connect-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'self'"

# Allow only logged-in users with role admin or editor to access /admin
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true
  [redirects.conditions]
    Role = ["admin", "editor"]

# Fallback for others: 404
[[redirects]]
  from = "/admin/*"
  to = "/404.html"
  status = 404

# Security headers for /admin only
[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: blob: https:; media-src 'self' blob: data:; font-src 'self' https://fonts.gstatic.com data:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://identity.netlify.com https://cdn.jsdelivr.net; connect-src 'self' blob: https://api.netlify.com https://identity.netlify.com https://oauth.netlify.com https://unpkg.com https://cdn.jsdelivr.net https://*.netlify.app https://netlifystatus.com https://api.netlifystatus.com; frame-src 'self' https://identity.netlify.com; worker-src 'self' blob:; base-uri 'self'; form-action 'self'; frame-ancestors 'self'"

[[
  headers
]]
  for = "/data/*.json"
  [headers.values]
    Cache-Control = "no-store, must-revalidate"
