backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "gallery"
    label: "Gallery"
    files:
      - file: "data/gallery.json"
        label: "Gallery Photos"
        name: "photos"
        fields:
          - label: Photos
            name: photos
            widget: list
            summary: "{{fields.group}} - {{fields.caption}}"
            fields:
              - { label: Group, name: group, widget: select, options: ["photoshoots","brand"], default: "photoshoots"}
              - label: Image
                name: src
                widget: image
                media_folder: "assets/images"
                public_folder: "/assets/images"

              - { label: Alt text, name: alt, widget: string, required: false }
              - { label: Caption, name: caption, widget: string, required: false }
              - { label: Order, name: order, widget: number, required: false, min: 0 }