backend:
  name: git-gateway
  branch: main

media_folder: "assets/gallery"
public_folder: "/assets/gallery"
media_folder_relative: false

collections:
  - name: "gallery"
    label: "Gallery"
    files:
      - file: "data/gallery.json"
        label: "Gallery Photos"
        name: "photos"
        fields:
          - label: "Photoshoots"
            name: "photoshoots"
            widget: list
            summary: "PS - {{fields.caption}}"
            fields:
              - label: "Image"
                name: "src"
                widget: "image"
                media_folder: "assets/gallery/photoshoots"
                public_folder: "/assets/gallery/photoshoots"
              - { label: Alt text, name: alt, widget: string, required: false }
              - { label: Caption, name: caption, widget: string, required: false }
              - { label: Order, name: order, widget: number, required: false, min: 0 }

          - label: "Brand"
            name: "brand"
            widget: list
            summary: "Brand - {{fields.caption}}"
            fields:
              - label: "Image"
                name: "src"
                widget: "image"
                media_folder: "assets/gallery/brand-shoots"
                public_folder: "/assets/gallery/brand-shoots"
              - { label: Alt text, name: alt, widget: string, required: false }
              - { label: Caption, name: caption, widget: string, required: false }
              - { label: Order, name: order, widget: number, required: false, min: 0 }